version: '3.7'
services:
  backend:
    build:
      context: ./backend
      args:
        dt_tenant: da982f2e-adc0-4062-a06c-67889dfe4e1a
        dt_url: spa-equinor.kanari.com
        azappconfig:
    ports:
      - '5000:5000'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AzureAd__ClientSecret:
  frontend:
    build:
      context: ./frontend
      args:
        dt_tenant: da982f2e-adc0-4062-a06c-67889dfe4e1a
        dt_url: spa-equinor.kanari.com
    depends_on:
      - backend
    ports:
      - '3000:3000'
