version: '3.7'
services:
  backend:
    build:
      context: ./backend
      args:
        azappconfig:
    ports:
      - '5000:5000'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AzureAd__ClientSecret:
