apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: dcd
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: qa
      build:
        from: main
    - name: prod
      build:
        from: main

  privateImageHubs:
    crdcd.azurecr.io:
      username: crdcd
      email: radix@statoilsrm.onmicrosoft.com

  components:
    - name: backend
      image: crdcd.azurecr.io/backend:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 5000
      publicPort: http
      variables:
        ASPNETCORE_ENVIRONMENT: "Development"
      environmentConfig:
        - environment: dev
          imageTagName: ci-release
          variables:
            AppConfiguration__Environment: "radix-dev"
          resources:
            requests:
              memory: "700Mi"
              cpu: "500m"
            limits:
              memory: "3000Mi"
              cpu: "1000m"
        - environment: qa
          imageTagName: qa-release
          variables:
            AppConfiguration__Environment: "radix-qa"
          resources:
            requests:
              memory: "700Mi"
              cpu: "500m"
            limits:
              memory: "3000Mi"
              cpu: "1000m"
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 6
        - environment: prod
          imageTagName: prod-release
          variables:
            AppConfiguration__Environment: "radix-prod"
            ASPNETCORE_ENVIRONMENT: "Production"
          resources:
            requests:
              memory: "700Mi"
              cpu: "500m"
            limits:
              memory: "3000Mi"
              cpu: "1000m"
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 6
      secrets:
        - AppConfiguration__ConnectionString
        - AZURE_CLIENT_ID
        - AZURE_TENANT_ID
        - AZURE_CLIENT_SECRET
