/* This file is autogenerated by the backend. Do not modify manually. */

export enum ProfileTypes {
    AdditionalOPEXCostProfile = "AdditionalOPEXCostProfile",
    AdditionalProductionProfileGas = "AdditionalProductionProfileGas",
    AdditionalProductionProfileOil = "AdditionalProductionProfileOil",
    AppraisalWellCostProfile = "AppraisalWellCostProfile",
    CalculatedTotalCostCostProfileUsd = "CalculatedTotalCostCostProfileUsd",
    CalculatedTotalIncomeCostProfileUsd = "CalculatedTotalIncomeCostProfileUsd",
    CessationOffshoreFacilitiesCost = "CessationOffshoreFacilitiesCost",
    CessationOffshoreFacilitiesCostOverride = "CessationOffshoreFacilitiesCostOverride",
    CessationOnshoreFacilitiesCostProfile = "CessationOnshoreFacilitiesCostProfile",
    CessationWellsCost = "CessationWellsCost",
    CessationWellsCostOverride = "CessationWellsCostOverride",
    Co2Emissions = "Co2Emissions",
    Co2EmissionsOverride = "Co2EmissionsOverride",
    Co2Intensity = "Co2Intensity",
    CountryOfficeCost = "CountryOfficeCost",
    DeferredGasProduction = "DeferredGasProduction",
    DeferredOilProduction = "DeferredOilProduction",
    DevelopmentRigMobDemob = "DevelopmentRigMobDemob",
    DevelopmentRigMobDemobOverride = "DevelopmentRigMobDemobOverride",
    DevelopmentRigUpgradingCostProfile = "DevelopmentRigUpgradingCostProfile",
    DevelopmentRigUpgradingCostProfileOverride = "DevelopmentRigUpgradingCostProfileOverride",
    ExplorationRigMobDemob = "ExplorationRigMobDemob",
    ExplorationRigMobDemobOverride = "ExplorationRigMobDemobOverride",
    ExplorationRigUpgradingCostProfile = "ExplorationRigUpgradingCostProfile",
    ExplorationRigUpgradingCostProfileOverride = "ExplorationRigUpgradingCostProfileOverride",
    ExplorationWellCostProfile = "ExplorationWellCostProfile",
    FuelFlaringAndLosses = "FuelFlaringAndLosses",
    FuelFlaringAndLossesOverride = "FuelFlaringAndLossesOverride",
    GAndGAdminCost = "GAndGAdminCost",
    GAndGAdminCostOverride = "GAndGAdminCostOverride",
    GasInjectorCostProfile = "GasInjectorCostProfile",
    GasInjectorCostProfileOverride = "GasInjectorCostProfileOverride",
    GasProducerCostProfile = "GasProducerCostProfile",
    GasProducerCostProfileOverride = "GasProducerCostProfileOverride",
    HistoricCostCostProfile = "HistoricCostCostProfile",
    ImportedElectricity = "ImportedElectricity",
    ImportedElectricityOverride = "ImportedElectricityOverride",
    NetSalesGas = "NetSalesGas",
    NetSalesGasOverride = "NetSalesGasOverride",
    OffshoreFacilitiesOperationsCostProfile = "OffshoreFacilitiesOperationsCostProfile",
    OffshoreFacilitiesOperationsCostProfileOverride = "OffshoreFacilitiesOperationsCostProfileOverride",
    OilProducerCostProfile = "OilProducerCostProfile",
    OilProducerCostProfileOverride = "OilProducerCostProfileOverride",
    OnshorePowerSupplyCostProfile = "OnshorePowerSupplyCostProfile",
    OnshorePowerSupplyCostProfileOverride = "OnshorePowerSupplyCostProfileOverride",
    OnshoreRelatedOPEXCostProfile = "OnshoreRelatedOPEXCostProfile",
    ProductionProfileGas = "ProductionProfileGas",
    ProductionProfileNgl = "ProductionProfileNgl",
    ProductionProfileOil = "ProductionProfileOil",
    ProductionProfileWater = "ProductionProfileWater",
    ProductionProfileWaterInjection = "ProductionProfileWaterInjection",
    ProjectSpecificDrillingCostProfile = "ProjectSpecificDrillingCostProfile",
    SeismicAcquisitionAndProcessing = "SeismicAcquisitionAndProcessing",
    SidetrackCostProfile = "SidetrackCostProfile",
    SubstructureCessationCostProfile = "SubstructureCessationCostProfile",
    SubstructureCostProfile = "SubstructureCostProfile",
    SubstructureCostProfileOverride = "SubstructureCostProfileOverride",
    SurfCessationCostProfile = "SurfCessationCostProfile",
    SurfCostProfile = "SurfCostProfile",
    SurfCostProfileOverride = "SurfCostProfileOverride",
    TopsideCessationCostProfile = "TopsideCessationCostProfile",
    TopsideCostProfile = "TopsideCostProfile",
    TopsideCostProfileOverride = "TopsideCostProfileOverride",
    TotalFeasibilityAndConceptStudies = "TotalFeasibilityAndConceptStudies",
    TotalFeasibilityAndConceptStudiesOverride = "TotalFeasibilityAndConceptStudiesOverride",
    TotalFEEDStudies = "TotalFEEDStudies",
    TotalFEEDStudiesOverride = "TotalFEEDStudiesOverride",
    TotalOtherStudiesCostProfile = "TotalOtherStudiesCostProfile",
    TransportCessationCostProfile = "TransportCessationCostProfile",
    TransportCostProfile = "TransportCostProfile",
    TransportCostProfileOverride = "TransportCostProfileOverride",
    WaterInjectorCostProfile = "WaterInjectorCostProfile",
    WaterInjectorCostProfileOverride = "WaterInjectorCostProfileOverride",
    WellInterventionCostProfile = "WellInterventionCostProfile",
    WellInterventionCostProfileOverride = "WellInterventionCostProfileOverride",
}

export enum ArtificialLift {
    NoArtificialLift = 0,
    GasLift = 1,
    ElectricalSubmergedPumps = 2,
    SubseaBoosterPumps = 3,
}

export enum CampaignCostType {
    RigUpgrading = 0,
    RigMobDemob = 1,
}

export enum CampaignType {
    DevelopmentCampaign = 1,
    ExplorationCampaign = 2,
}

export enum Concept {
    NO_CONCEPT = 0,
    TIE_BACK = 1,
    JACKET = 2,
    GBS = 3,
    TLP = 4,
    SPAR = 5,
    SEMI = 6,
    CIRCULAR_BARGE = 7,
    BARGE = 8,
    FPSO = 9,
    TANKER = 10,
    JACK_UP = 11,
    SUBSEA_TO_SHORE = 12,
}

export enum Currency {
    NOK = 1,
    USD = 2,
}

export enum GasSolution {
    Export = 0,
    Injection = 1,
}

export enum InternalProjectPhase {
    APbo = 0,
    BOR = 1,
    VPbo = 2,
}

export enum Maturity {
    A = 0,
    B = 1,
    C = 2,
    D = 3,
}

export enum NoAccessReason {
    ProjectDoesNotExist = 1,
    ClassificationInternal = 2,
    ClassificationRestricted = 3,
    ClassificationConfidential = 4,
}

export enum PhysUnit {
    SI = 0,
    OilField = 1,
}

export enum ProductionFlowline {
    No_production_flowline = 0,
    Carbon = 1,
    SSClad = 2,
    Cr13 = 3,
    Carbon_Insulation = 4,
    SSClad_Insulation = 5,
    Cr13_Insulation = 6,
    Carbon_Insulation_DEH = 7,
    SSClad_Insulation_DEH = 8,
    Cr13_Insulation_DEH = 9,
    Carbon_PIP = 10,
    SSClad_PIP = 11,
    Cr13_PIP = 12,
    HDPELinedCS = 13,
}

export enum ProductionStrategyOverview {
    Depletion = 0,
    WaterInjection = 1,
    GasInjection = 2,
    WAG = 3,
    Mixed = 4,
}

export enum ProjectCategory {
    Null = 0,
    Brownfield = 1,
    Cessation = 2,
    DrillingUpgrade = 3,
    Onshore = 4,
    Pipeline = 5,
    PlatformFpso = 6,
    Subsea = 7,
    Solar = 8,
    Co2Storage = 9,
    Efuel = 10,
    Nuclear = 11,
    Co2Capture = 12,
    Fpso = 13,
    Hydrogen = 14,
    Hse = 15,
    OffshoreWind = 16,
    Platform = 17,
    PowerFromShore = 18,
    TieIn = 19,
    RenewableOther = 20,
    Ccs = 21,
}

export enum ProjectClassification {
    Open = 0,
    Internal = 1,
    Restricted = 2,
    Confidential = 3,
}

export enum ProjectMemberRole {
    Observer = 0,
    Editor = 1,
}

export enum ProjectPhase {
    Null = 0,
    BidPreparations = 1,
    BusinessIdentification = 2,
    BusinessPlanning = 3,
    ConceptPlanning = 4,
    ConcessionNegotiations = 5,
    Definition = 6,
    Execution = 7,
    Operation = 8,
    ScreeningBusinessOpportunities = 9,
}

export enum Source {
    ConceptApp = 0,
    Prosp = 1,
}

export enum WellCategory {
    Oil_Producer = 0,
    Gas_Producer = 1,
    Water_Injector = 2,
    Gas_Injector = 3,
    Exploration_Well = 4,
    Appraisal_Well = 5,
    Sidetrack = 6,
    RigMobDemob = 7,
}
