/* This file is autogenerated by the backend. Do not modify manually. */

declare namespace ProfileTypes {
    export const AdditionalOPEXCostProfile = "AdditionalOPEXCostProfile"
    export const AdditionalProductionProfileGas = "AdditionalProductionProfileGas"
    export const AdditionalProductionProfileOil = "AdditionalProductionProfileOil"
    export const AppraisalWellCostProfile = "AppraisalWellCostProfile"
    export const CalculatedTotalCostCostProfile = "CalculatedTotalCostCostProfile"
    export const CalculatedTotalIncomeCostProfile = "CalculatedTotalIncomeCostProfile"
    export const CessationOffshoreFacilitiesCost = "CessationOffshoreFacilitiesCost"
    export const CessationOffshoreFacilitiesCostOverride = "CessationOffshoreFacilitiesCostOverride"
    export const CessationOnshoreFacilitiesCostProfile = "CessationOnshoreFacilitiesCostProfile"
    export const CessationWellsCost = "CessationWellsCost"
    export const CessationWellsCostOverride = "CessationWellsCostOverride"
    export const Co2Emissions = "Co2Emissions"
    export const Co2EmissionsOverride = "Co2EmissionsOverride"
    export const Co2Intensity = "Co2Intensity"
    export const CountryOfficeCost = "CountryOfficeCost"
    export const DeferredGasProduction = "DeferredGasProduction"
    export const DeferredOilProduction = "DeferredOilProduction"
    export const DevelopmentRigMobDemob = "DevelopmentRigMobDemob"
    export const DevelopmentRigMobDemobOverride = "DevelopmentRigMobDemobOverride"
    export const DevelopmentRigUpgradingCostProfile = "DevelopmentRigUpgradingCostProfile"
    export const DevelopmentRigUpgradingCostProfileOverride = "DevelopmentRigUpgradingCostProfileOverride"
    export const ExplorationRigMobDemob = "ExplorationRigMobDemob"
    export const ExplorationRigMobDemobOverride = "ExplorationRigMobDemobOverride"
    export const ExplorationRigUpgradingCostProfile = "ExplorationRigUpgradingCostProfile"
    export const ExplorationRigUpgradingCostProfileOverride = "ExplorationRigUpgradingCostProfileOverride"
    export const ExplorationWellCostProfile = "ExplorationWellCostProfile"
    export const FuelFlaringAndLosses = "FuelFlaringAndLosses"
    export const FuelFlaringAndLossesOverride = "FuelFlaringAndLossesOverride"
    export const GAndGAdminCost = "GAndGAdminCost"
    export const GAndGAdminCostOverride = "GAndGAdminCostOverride"
    export const GasInjectorCostProfile = "GasInjectorCostProfile"
    export const GasInjectorCostProfileOverride = "GasInjectorCostProfileOverride"
    export const GasProducerCostProfile = "GasProducerCostProfile"
    export const GasProducerCostProfileOverride = "GasProducerCostProfileOverride"
    export const HistoricCostCostProfile = "HistoricCostCostProfile"
    export const ImportedElectricity = "ImportedElectricity"
    export const ImportedElectricityOverride = "ImportedElectricityOverride"
    export const NetSalesGas = "NetSalesGas"
    export const NetSalesGasOverride = "NetSalesGasOverride"
    export const OffshoreFacilitiesOperationsCostProfile = "OffshoreFacilitiesOperationsCostProfile"
    export const OffshoreFacilitiesOperationsCostProfileOverride = "OffshoreFacilitiesOperationsCostProfileOverride"
    export const OilProducerCostProfile = "OilProducerCostProfile"
    export const OilProducerCostProfileOverride = "OilProducerCostProfileOverride"
    export const OnshorePowerSupplyCostProfile = "OnshorePowerSupplyCostProfile"
    export const OnshorePowerSupplyCostProfileOverride = "OnshorePowerSupplyCostProfileOverride"
    export const OnshoreRelatedOPEXCostProfile = "OnshoreRelatedOPEXCostProfile"
    export const ProductionProfileGas = "ProductionProfileGas"
    export const ProductionProfileNgl = "ProductionProfileNgl"
    export const ProductionProfileOil = "ProductionProfileOil"
    export const ProductionProfileWater = "ProductionProfileWater"
    export const ProductionProfileWaterInjection = "ProductionProfileWaterInjection"
    export const ProjectSpecificDrillingCostProfile = "ProjectSpecificDrillingCostProfile"
    export const SeismicAcquisitionAndProcessing = "SeismicAcquisitionAndProcessing"
    export const SidetrackCostProfile = "SidetrackCostProfile"
    export const SubstructureCessationCostProfile = "SubstructureCessationCostProfile"
    export const SubstructureCostProfile = "SubstructureCostProfile"
    export const SubstructureCostProfileOverride = "SubstructureCostProfileOverride"
    export const SurfCessationCostProfile = "SurfCessationCostProfile"
    export const SurfCostProfile = "SurfCostProfile"
    export const SurfCostProfileOverride = "SurfCostProfileOverride"
    export const TopsideCessationCostProfile = "TopsideCessationCostProfile"
    export const TopsideCostProfile = "TopsideCostProfile"
    export const TopsideCostProfileOverride = "TopsideCostProfileOverride"
    export const TotalFeasibilityAndConceptStudies = "TotalFeasibilityAndConceptStudies"
    export const TotalFeasibilityAndConceptStudiesOverride = "TotalFeasibilityAndConceptStudiesOverride"
    export const TotalFEEDStudies = "TotalFEEDStudies"
    export const TotalFEEDStudiesOverride = "TotalFEEDStudiesOverride"
    export const TotalOtherStudiesCostProfile = "TotalOtherStudiesCostProfile"
    export const TransportCessationCostProfile = "TransportCessationCostProfile"
    export const TransportCostProfile = "TransportCostProfile"
    export const TransportCostProfileOverride = "TransportCostProfileOverride"
    export const WaterInjectorCostProfile = "WaterInjectorCostProfile"
    export const WaterInjectorCostProfileOverride = "WaterInjectorCostProfileOverride"
    export const WellInterventionCostProfile = "WellInterventionCostProfile"
    export const WellInterventionCostProfileOverride = "WellInterventionCostProfileOverride"

    export type ProfileTypesValues =
        "AdditionalOPEXCostProfile" |
        "AdditionalProductionProfileGas" |
        "AdditionalProductionProfileOil" |
        "AppraisalWellCostProfile" |
        "CalculatedTotalCostCostProfile" |
        "CalculatedTotalIncomeCostProfile" |
        "CessationOffshoreFacilitiesCost" |
        "CessationOffshoreFacilitiesCostOverride" |
        "CessationOnshoreFacilitiesCostProfile" |
        "CessationWellsCost" |
        "CessationWellsCostOverride" |
        "Co2Emissions" |
        "Co2EmissionsOverride" |
        "Co2Intensity" |
        "CountryOfficeCost" |
        "DeferredGasProduction" |
        "DeferredOilProduction" |
        "DevelopmentRigMobDemob" |
        "DevelopmentRigMobDemobOverride" |
        "DevelopmentRigUpgradingCostProfile" |
        "DevelopmentRigUpgradingCostProfileOverride" |
        "ExplorationRigMobDemob" |
        "ExplorationRigMobDemobOverride" |
        "ExplorationRigUpgradingCostProfile" |
        "ExplorationRigUpgradingCostProfileOverride" |
        "ExplorationWellCostProfile" |
        "FuelFlaringAndLosses" |
        "FuelFlaringAndLossesOverride" |
        "GAndGAdminCost" |
        "GAndGAdminCostOverride" |
        "GasInjectorCostProfile" |
        "GasInjectorCostProfileOverride" |
        "GasProducerCostProfile" |
        "GasProducerCostProfileOverride" |
        "HistoricCostCostProfile" |
        "ImportedElectricity" |
        "ImportedElectricityOverride" |
        "NetSalesGas" |
        "NetSalesGasOverride" |
        "OffshoreFacilitiesOperationsCostProfile" |
        "OffshoreFacilitiesOperationsCostProfileOverride" |
        "OilProducerCostProfile" |
        "OilProducerCostProfileOverride" |
        "OnshorePowerSupplyCostProfile" |
        "OnshorePowerSupplyCostProfileOverride" |
        "OnshoreRelatedOPEXCostProfile" |
        "ProductionProfileGas" |
        "ProductionProfileNgl" |
        "ProductionProfileOil" |
        "ProductionProfileWater" |
        "ProductionProfileWaterInjection" |
        "ProjectSpecificDrillingCostProfile" |
        "SeismicAcquisitionAndProcessing" |
        "SidetrackCostProfile" |
        "SubstructureCessationCostProfile" |
        "SubstructureCostProfile" |
        "SubstructureCostProfileOverride" |
        "SurfCessationCostProfile" |
        "SurfCostProfile" |
        "SurfCostProfileOverride" |
        "TopsideCessationCostProfile" |
        "TopsideCostProfile" |
        "TopsideCostProfileOverride" |
        "TotalFeasibilityAndConceptStudies" |
        "TotalFeasibilityAndConceptStudiesOverride" |
        "TotalFEEDStudies" |
        "TotalFEEDStudiesOverride" |
        "TotalOtherStudiesCostProfile" |
        "TransportCessationCostProfile" |
        "TransportCostProfile" |
        "TransportCostProfileOverride" |
        "WaterInjectorCostProfile" |
        "WaterInjectorCostProfileOverride" |
        "WellInterventionCostProfile" |
        "WellInterventionCostProfileOverride"
}
