parameters:
  - name: imageTag
  - name: webAppName
  - name: environment
  - name: serviceConnection
  - name: name

stages:
  - stage: ${{ parameters.name }}
    displayName: "Deploy App ${{ parameters.environment }}"
    jobs:
      - job: "DeployContainerBackend"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: step-deploycontainer.yml
            parameters:
              imageName: "dcd_backend"
              imageTag: $(Build.BuildId)
              webAppName: "${{ parameters.webAppName }}-backend-${{ parameters.environment }}"
              serviceConnection: "dcd-pipeline-sp"
              name: "DeployBackend_${{ parameters.environment }}"
          - template: step-swapslots.yml
            parameters:
              webAppName: "${{ parameters.webAppName }}-backend-${{ parameters.environment }}"
              serviceConnection: "dcd-pipeline-sp"
              name: "DeployBackend_${{ parameters.environment }}"
      - job: "DeployContainerFrontend"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: step-deploycontainer.yml
            parameters:
              imageName: "dcd_frontend"
              imageTag: $(Build.BuildId)
              webAppName: "${{ parameters.webAppName }}-frontend-${{ parameters.environment }}"
              serviceConnection: "dcd-pipeline-sp"
              name: "DeployFrontend_${{ parameters.environment }}"
          - template: step-swapslots.yml
            parameters:
              webAppName: "${{ parameters.webAppName }}-frontend-${{ parameters.environment }}"
              serviceConnection: "dcd-pipeline-sp"
              name: "DeployFrontend_${{ parameters.environment }}"
