trigger:
    branches:
        include:
            - main
    tags:
        include:
            - v*
    paths:
        exclude:
            - /*
pool:
    vmImage: "ubuntu-latest"

pr: none

variables:
  - group: DCD
  - group: DCD-KeyVault

stages:
  - template: templates/stage-build-fusion.yml
    parameters:
      workSpace: $(Pipeline.Workspace)
      buildId: $(Build.BuildId)
      dt_tenant: $(dynatracePreProdTenantId)
      dt_password: $(dynatracePreProdToken)
      dt_url: $(dynatrace_baseurl)
      azAppConfig: $(azureAppConfig)
      sourcesDirectory: $(Build.SourcesDirectory)
      name: "DCD"

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_CI
        envshortname: ci
        envfullname: CI
        portalUrl: $(FusionCIPortalUrl)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        DBContext: $(DbConnectionStringDev)
        FusionEnvId: $(FusionAppIdCi)
        FusionServiceConnection: 'conceptapp-preprod'
        ContainerTag: "release"
        DynatraceToken: $(dynatracePreProdToken)
        DynatraceTenantId: $(dynatracePreProdTenantId)
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_QA
        envshortname: qa
        envfullname: QA
        portalUrl: $(FusionQAPortalUrl)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        DBContext: $(DbConnectionStringQa)
        FusionEnvId: $(FusionAppIdQA)
        FusionServiceConnection: 'conceptapp-preprod'
        ContainerTag: "release"
        DynatraceToken: $(dynatracePreProdToken)
        DynatraceTenantId: $(dynatracePreProdTenantId)
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_Prod
        envshortname: prod
        envfullname: Production
        portalUrl: $(FusionPRDPortalUrl)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        DBContext: $(DbConnectionStringProd)
        FusionEnvId: $(FusionAppIdFPRD)
        FusionServiceConnection: 'conceptapp-prod'
        ContainerTag: "release"
        DynatraceToken: $(dynatrace-prod-token)
        DynatraceTenantId: $(dynatrace_tenant)
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)