trigger:
    branches:
        include:
            - main
    tags:
        include:
            - v*
    paths:
        exclude:
            - /*
pool:
    vmImage: "ubuntu-latest"

pr: none

variables:
  - group: DCD
  - group: DCD-KeyVault

stages:
  - stage: Deploy_CI
    variables:
      - group: DCD-CI
    jobs:
      - template: templates/stage-deploy-fusion.yml
        parameters:
            appName: Deploy_CI
            fusionEnvironment: ci
            envshortname: ci
            envfullname: CI
            FusionEnvId: $(FusionAppId)
            buildId: $(Build.BuildId)
            radixToken: $(RadixToken)
            branch: main
            ContainerTag: "release"
            SpAzureClientId: $(SpPreProdAzureClientId)
            SpAzureClientSecret: $(SpPreProdAzureClientSecret)
            AzureTenantId: $(SpAzureTenantId)
            ResourceGroupName: "rg-fapps-dcd-preprod"
            SqlAdminPassword: $(SqlAdminPassword)
            ClientSecret: $(ApiClientSecret)
