trigger:
    branches:
        include:
            - main
    tags:
        include:
            - v*
    paths:
        exclude:
            - /*
pool:
    vmImage: "ubuntu-latest"

pr: none

variables:
  - group: DCD
  - group: DCD-KeyVault

stages:
  - template: templates/stage-build-fusion.yml
    parameters:
      workSpace: $(Pipeline.Workspace)
      buildId: $(Build.BuildId)
      dt_tenant: $(dynatracePreProdTenantId)
      dt_password: $(dynatracePreProdToken)
      dt_url: $(dynatrace_baseurl)
      azAppConfig: $(azureAppConfig)
      sourcesDirectory: $(Build.SourcesDirectory)
      name: "DCD"

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_CI
        envshortname: ci
        envfullname: CI
        portalUrl: $(FusionCIPortalUrl)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        FusionEnvId: $(FusionAppIdCi)
        FusionServiceConnection: 'conceptapp-preprod'
        ContainerTag: "release"
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)
        frontendVersion: $[ stageDependencies.DCD.outputs['Build_Fusion_App.UpdateVersion.frontendVersion'] ]

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_QA
        envshortname: qa
        envfullname: QA
        portalUrl: $(FusionQAPortalUrl)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        FusionEnvId: $(FusionAppIdQA)
        FusionServiceConnection: 'conceptapp-preprod'
        ContainerTag: "release"
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)
        frontendVersion: $[ stageDependencies.DCD.Build_Fusion_App.outputs['frontendVersion'] ]

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_Prod
        envshortname: prod
        envfullname: Production
        portalUrl: $(FusionPRDPortalUrl)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        FusionEnvId: $(FusionAppIdFPRD)
        FusionServiceConnection: 'conceptapp-prod'
        ContainerTag: "release"
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)
        frontendVersion: $[ stageDependencies.DCD.Build_Fusion_App.outputs['frontendVersion'] ]
