trigger:
    branches:
        include:
            - main
    tags:
        include:
            - v*
    paths:
        exclude:
            - /*
pool:
    vmImage: "ubuntu-latest"

pr: none

variables:
  - group: DCD
  - group: DCD-KeyVault

stages:
  - template: templates/stage-build-fusion.yml
    parameters:
      workSpace: $(Pipeline.Workspace)
      buildId: $(Build.BuildId)
      azAppConfig: $(azureAppConfig)
      sourcesDirectory: $(Build.SourcesDirectory)
      name: "DCD"

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_CI
        fusionEnvironment: ci
        envshortname: ci
        envfullname: CI
        FusionEnvId: $(FusionAppIdCi)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        ContainerTag: "release"
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_QA
        fusionEnvironment: fqa
        envshortname: qa
        envfullname: QA
        FusionEnvId: $(FusionAppIdQA)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        ContainerTag: "release"
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_Prod
        fusionEnvironment: fprd
        envshortname: prod
        envfullname: Production
        FusionEnvId: $(FusionAppIdFPRD)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        ContainerTag: "release"
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)
