trigger:
    branches:
        include:
            - main
    tags:
        include:
            - v*
    paths:
        exclude:
            - /*
pool:
    vmImage: "ubuntu-latest"

pr: none

variables:
  - group: DCD

stages:
  - template: templates/stage-build-fusion.yml
    parameters:
      azAppConfig: $(azureAppConfigConnString)

  - stage: Deploy_CI
    variables:
      - group: DCD-CI
    jobs:
      - template: templates/stage-deploy-fusion.yml
        parameters:
            fusionEnvironment: ci
            envshortname: ci
            envfullname: CI
            FusionEnvId: $(FusionAppId)
            SpAzureClientId: $(SpPreProdAzureClientId)
            SpAzureClientSecret: $(SpPreProdAzureClientSecret)
            AzureTenantId: $(SpAzureTenantId)
            ResourceGroupName: "rg-fapps-dcd-preprod"
            SqlAdminPassword: $(SqlAdminPassword)
            ClientSecret: $(ApiClientSecret)

  - stage: Deploy_QA
    variables:
      - group: DCD-QA
    jobs:
      - template: templates/stage-deploy-fusion.yml
        parameters:
            fusionEnvironment: fqa
            envshortname: qa
            envfullname: QA
            FusionEnvId: $(FusionAppIdQA)
            SpAzureClientId: $(SpPreProdAzureClientId)
            SpAzureClientSecret: $(SpPreProdAzureClientSecret)
            AzureTenantId: $(SpAzureTenantId)
            ResourceGroupName: "rg-fapps-dcd-preprod"
            SqlAdminPassword: $(SqlAdminPassword)
            ClientSecret: $(ApiClientSecret)

  - stage: Deploy_Prod
    variables:
      - group: DCD-Prod
    jobs:
      - template: templates/stage-deploy-fusion.yml
        parameters:
            fusionEnvironment: fprd
            envshortname: prod
            envfullname: Production
            FusionEnvId: $(FusionAppIdFPRD)
            SpAzureClientId: $(SpPreProdAzureClientId)
            SpAzureClientSecret: $(SpPreProdAzureClientSecret)
            AzureTenantId: $(SpAzureTenantId)
            ResourceGroupName: "rg-fapps-dcd-prod"
            SqlAdminPassword: $(SqlAdminPassword)
            ClientSecret: $(ApiClientSecret)
