trigger:
    branches:
        include:
            - main
    tags:
        include:
            - v*
    paths:
        exclude:
            - /*
pool:
    vmImage: "ubuntu-latest"

pr: none

variables:
  - group: DCD
  - group: DCD-KeyVault

stages:
  - template: templates/stage-build-fusion.yml
    parameters:
      workSpace: $(Pipeline.Workspace)
      buildId: $(Build.BuildId)
      azAppConfig: $(azureAppConfigConnString)
      sourcesDirectory: $(Build.SourcesDirectory)
      name: "DCD"

  - stage: Deploy_CI
    variables:
      - group: DCD-CI
    jobs:
      - template: templates/stage-deploy-fusion.yml
        parameters:
            appName: Deploy_CI
            fusionEnvironment: ci
            envshortname: ci
            envfullname: CI
            FusionEnvId: $(FusionAppId)
            buildId: $(Build.BuildId)
            radixToken: $(RadixToken)
            branch: main
            ContainerTag: "release"
            SpAzureClientId: $(SpPreProdAzureClientId)
            SpAzureClientSecret: $(SpPreProdAzureClientSecret)
            AzureTenantId: $(SpAzureTenantId)
            ResourceGroupName: "rg-fapps-dcd-preprod"
            SqlAdminPassword: $(SqlAdminPassword)
            ClientSecret: $(ApiClientSecret)

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_QA
        fusionEnvironment: fqa
        envshortname: qa
        envfullname: QA
        FusionEnvId: $(FusionAppIdQA)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        ContainerTag: "release"
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)
        ResourceGroupName: rg-fapps-dcd-preprod
        SqlAdminPassword: $(SqlAdminPasswordQa)
        ClientSecret: $(ApiClientSecretPreprod)

  - template: templates/stage-deploy-fusion.yml
    parameters:
        appName: Deploy_Prod
        fusionEnvironment: fprd
        envshortname: prod
        envfullname: Production
        FusionEnvId: $(FusionAppIdFPRD)
        buildId: $(Build.BuildId)
        radixToken: $(RadixToken)
        branch: main
        ContainerTag: "release"
        SpAzureClientId: $(SpPreProdAzureClientId)
        SpAzureClientSecret: $(SpPreProdAzureClientSecret)
        AzureTenantId: $(SpAzureTenantId)
        ResourceGroupName: rg-fapps-dcd-prod
        SqlAdminPassword: $(SqlAdminPasswordProd)
        ClientSecret: $(ApiClientSecretProd)
