/* This file is autogenerated by the backend. Do not modify manually. */

export enum NoAccessReason {
    ProjectDoesNotExist = 1,
    ClassificationInternal = 2,
    ClassificationRestricted = 3,
    ClassificationConfidential = 4,
}

export enum ProjectPhase {
    Null = 0,
    BidPreparations = 1,
    BusinessIdentification = 2,
    BusinessPlanning = 3,
    ConceptPlanning = 4,
    ConcessionNegotiations = 5,
    Definition = 6,
    Execution = 7,
    Operation = 8,
    ScreeningBusinessOpportunities = 9,
}

