import { ProfileTypes } from "@/Models/enums"

export const profileNameMap = new Map<string, string>([
    ["additionalOPEXCostProfile", ProfileTypes.AdditionalOPEXCostProfile],
    ["additionalProductionProfileGas", ProfileTypes.AdditionalProductionProfileGas],
    ["additionalProductionProfileOil", ProfileTypes.AdditionalProductionProfileOil],
    ["cessationOnshoreFacilitiesCostProfile", ProfileTypes.CessationOnshoreFacilitiesCostProfile],
    ["countryOfficeCost", ProfileTypes.CountryOfficeCost],
    ["deferredGasProduction", ProfileTypes.DeferredGasProduction],
    ["deferredOilProduction", ProfileTypes.DeferredOilProduction],
    ["onshoreRelatedOPEXCostProfile", ProfileTypes.OnshoreRelatedOPEXCostProfile],
    ["productionProfileGas", ProfileTypes.ProductionProfileGas],
    ["productionProfileOil", ProfileTypes.ProductionProfileOil],
    ["productionProfileWater", ProfileTypes.ProductionProfileWater],
    ["productionProfileWaterInjection", ProfileTypes.ProductionProfileWaterInjection],
    ["projectSpecificDrillingCostProfile", ProfileTypes.ProjectSpecificDrillingCostProfile],
    ["seismicAcquisitionAndProcessing", ProfileTypes.SeismicAcquisitionAndProcessing],
    ["totalOtherStudiesCostProfile", ProfileTypes.TotalOtherStudiesCostProfile],
])

export const overrideProfileNameMap = new Map<string, string>([
    ["cessationOffshoreFacilitiesCostOverride", ProfileTypes.CessationOffshoreFacilitiesCostOverride],
    ["cessationWellsCostOverride", ProfileTypes.CessationWellsCostOverride],
    ["co2EmissionsOverride", ProfileTypes.Co2EmissionsOverride],
    ["gAndGAdminCost", ProfileTypes.GAndGAdminCostOverride],
    ["historicCostCostProfile", ProfileTypes.HistoricCostCostProfile],
    ["offshoreFacilitiesOperationsCostProfileOverride", ProfileTypes.OffshoreFacilitiesOperationsCostProfileOverride],
    ["onshorePowerSupplyCostOverride", ProfileTypes.OnshorePowerSupplyCostProfileOverride],
    ["productionProfileFuelFlaringAndLossesOverride", ProfileTypes.FuelFlaringAndLossesOverride],
    ["productionProfileImportedElectricityOverride", ProfileTypes.ImportedElectricityOverride],
    ["productionProfileNetSalesGasOverride", ProfileTypes.NetSalesGasOverride],
    ["substructureCostOverride", ProfileTypes.SubstructureCostProfileOverride],
    ["surfCostOverride", ProfileTypes.SurfCostProfileOverride],
    ["topsideCostOverride", ProfileTypes.TopsideCostProfileOverride],
    ["totalFeasibilityAndConceptStudiesOverride", ProfileTypes.TotalFeasibilityAndConceptStudiesOverride],
    ["totalFEEDStudiesOverride", ProfileTypes.TotalFEEDStudiesOverride],
    ["transportCostOverride", ProfileTypes.TransportCostProfileOverride],
    ["wellInterventionCostProfileOverride", ProfileTypes.WellInterventionCostProfileOverride],
    ["wellProjectGasInjectorCostOverride", ProfileTypes.GasInjectorCostProfileOverride],
    ["wellProjectGasProducerCostOverride", ProfileTypes.GasProducerCostProfileOverride],
    ["wellProjectOilProducerCostOverride", ProfileTypes.OilProducerCostProfileOverride],
    ["wellProjectWaterInjectorCostOverride", ProfileTypes.WaterInjectorCostProfileOverride],
])
