import { ProfileTypes } from "@/Models/enums"

export const ordinaryTimeSeriesTypes = [
    ProfileTypes.AdditionalProductionProfileGas,
    ProfileTypes.AdditionalOPEXCostProfile,
    ProfileTypes.AdditionalProductionProfileOil,
    ProfileTypes.CessationOnshoreFacilitiesCostProfile,
    ProfileTypes.CountryOfficeCost,
    ProfileTypes.HistoricCostCostProfile,
    ProfileTypes.DeferredGasProduction,
    ProfileTypes.DeferredOilProduction,
    ProfileTypes.OnshoreRelatedOPEXCostProfile,
    ProfileTypes.ProductionProfileGas,
    ProfileTypes.ProductionProfileOil,
    ProfileTypes.ProductionProfileWater,
    ProfileTypes.ProductionProfileWaterInjection,
    ProfileTypes.ProjectSpecificDrillingCostProfile,
    ProfileTypes.SeismicAcquisitionAndProcessing,
    ProfileTypes.TotalOtherStudiesCostProfile,
]

export const overrideTimeSeriesTypes = [
    ProfileTypes.CessationOffshoreFacilitiesCostOverride,
    ProfileTypes.CessationWellsCostOverride,
    ProfileTypes.Co2EmissionsOverride,
    ProfileTypes.GAndGAdminCostOverride,
    ProfileTypes.OffshoreFacilitiesOperationsCostProfileOverride,
    ProfileTypes.OnshorePowerSupplyCostProfileOverride,
    ProfileTypes.FuelFlaringAndLossesOverride,
    ProfileTypes.ImportedElectricityOverride,
    ProfileTypes.NetSalesGasOverride,
    ProfileTypes.SubstructureCostProfileOverride,
    ProfileTypes.SurfCostProfileOverride,
    ProfileTypes.TopsideCostProfileOverride,
    ProfileTypes.TotalFeasibilityAndConceptStudiesOverride,
    ProfileTypes.TotalFEEDStudiesOverride,
    ProfileTypes.TransportCostProfileOverride,
    ProfileTypes.WellInterventionCostProfileOverride,
    ProfileTypes.GasInjectorCostProfileOverride,
    ProfileTypes.GasProducerCostProfileOverride,
    ProfileTypes.OilProducerCostProfileOverride,
    ProfileTypes.WaterInjectorCostProfileOverride,
]
